version: 2

project_name: s3-proxy

force_token: github

before:
  hooks:
    - go mod download

builds:
  - binary: s3-proxy
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    flags:
      - -trimpath

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

dockers:
  - image_templates:
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
    use: buildx
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.created={{ .Date }}
    dockerfile: Dockerfile-goreleaser
    extra_files:
      - LICENSE
      - README.md
  - image_templates:
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
    use: buildx
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.created={{ .Date }}
    goarch: arm64
    dockerfile: Dockerfile-goreleaser
    extra_files:
      - LICENSE
      - README.md

docker_manifests:
  - name_template: "docker.io/dex4er/s3-proxy:v{{ .Version }}"
    image_templates:
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
  - name_template: "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}"
    image_templates:
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
  - name_template: "docker.io/dex4er/s3-proxy:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
  - name_template: "public.ecr.aws/dex4er/s3-proxy:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
  - name_template: "docker.io/dex4er/s3-proxy:v{{ .Major }}"
    image_templates:
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
  - name_template: "public.ecr.aws/dex4er/s3-proxy:v{{ .Major }}"
    image_templates:
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
  - name_template: docker.io/dex4er/s3-proxy:latest
    image_templates:
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "docker.io/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"
  - name_template: public.ecr.aws/dex4er/s3-proxy:latest
    image_templates:
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/s3-proxy:v{{ .Version }}-linux-arm64"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}.sha256"
  algorithm: sha256
  split: true

changelog:
  use: github
