FROM alpine:3.20 AS certs

RUN apk --no-cache add ca-certificates


FROM scratch

WORKDIR /

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY ./s3-proxy /s3-proxy
COPY ./LICENSE /README.md /

ENTRYPOINT ["/s3-proxy"]

LABEL \
  maintainer="Piotr Roszatycki <piotr.roszatycki@gmail.com>" \
  org.opencontainers.image.description="S3 proxy" \
  org.opencontainers.image.licenses="MIT" \
  org.opencontainers.image.source=https://github.com/dex4er/s3-proxy \
  org.opencontainers.image.title=s3-proxy \
  org.opencontainers.image.url=https://github.com/dex4er/s3-proxy \
  org.opencontainers.image.vendor=dex4er
